<?php

namespace JiraBundle\Repository;

/**
 * documentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class documentRepository extends \Doctrine\ORM\EntityRepository
{
}
