<?php

namespace JiraBundle\Repository;
use JiraBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * @return User[]
     */
    public function getAll() {
        return $this->getEntityManager()->getRepository(User::class)->findAll();
    }
}
