<?php

namespace JiraBundle\Repository;

use JiraBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * @return User[]
     */
    public function getAll()
    {
        return $this->getEntityManager()->getRepository(User::class)->findAll();
    }

    /**
     * @param $taskId
     * @return User[]
     */
    public function getByTask($taskId)
    {
        $users = $this->getEntityManager()->getRepository(User::class);
        return $users->findBy(array('task_id'=>$taskId));
    }

    /**
     * @return User|null
     */
    public function getByUserId($user_id,$task_id)
    {
        return $this->getEntityManager()->getRepository(User::class)->find(array("user_id"=>$user_id,"task_id" => $task_id));
    }
}
